### ISSUE TITLE
data preprocessing Index Error

### ISSUE THREAD

**Issue by surqing** [PhoebeGaoZhen/AttentionGRN#2]
```
****************************hHEP————HepG2-ChIP-seq-network————1000****************************
2 genes and 0 cells are included in origin expression data.

2 genes in low expression.


The top 500/1000 genes were selected in order of variance..........
Traceback (most recent call last):
  File "dataProcess_GRN_data1_AttentionGRN.py", line 64, in <module>
    utils.preprocess_DATA_AttentionGRN(result_path, gold_network_path, gene_expression_path, dataset_name, gene_order_path, Rank_num, pathHumanTF)
  File "/media/yjz/sur/GRN/AttentionGRN/data_preprocess/utils_data.py", line 749, in preprocess_DATA_AttentionGRN
    rank_list, significant_gene_list = get_gene_ranking(gene_order_path, low_express_gene_list, Rank_num, False)
  File "/media/yjz/sur/GRN/AttentionGRN/data_preprocess/utils_data.py", line 73, in get_gene_ranking
    if float(single_order_reader[1]) >= 0.01:
IndexError: list index out of range
```

**Comment by PhoebeGaoZhen** [comment]
We double-checked the code for data pre-processing and it worked fine. Can you provide more detailed operation process? It would be better if it was a screenshot so that we could examine the problem more carefully. Thank you so much.



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/12/2024 16:25 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [PhoebeGaoZhen/AttentionGRN] data preprocessing Index Error (Issue #2) |

****************************hHEP————HepG2-ChIP-seq-network————1000****************************
2 genes and 0 cells are included in origin expression data.

2 genes in low expression.


The top 500/1000 genes were selected in order of variance..........
Traceback (most recent call last):
  File "dataProcess_GRN_data1_AttentionGRN.py", line 64, in <module>
    utils.preprocess_DATA_AttentionGRN(result_path, gold_network_path, gene_expression_path, dataset_name, gene_order_path, Rank_num, pathHumanTF)
  File "/media/yjz/sur/GRN/AttentionGRN/data_preprocess/utils_data.py", line 749, in preprocess_DATA_AttentionGRN
    rank_list, significant_gene_list = get_gene_ranking(gene_order_path, low_express_gene_list, Rank_num, False)
  File "/media/yjz/sur/GRN/AttentionGRN/data_preprocess/utils_data.py", line 73, in get_gene_ranking
    if float(single_order_reader[1]) >= 0.01:
IndexError: list index out of range

**Comment by surqing** [comment]
![image](https://github.com/user-attachments/assets/60e8af7f-4270-4064-907d-74794fdeed14)
![image](https://github.com/user-attachments/assets/2e356ba0-f9dd-44d6-9374-6cc368de6241)
![image](https://github.com/user-attachments/assets/9800690e-51af-454d-92c1-aed304b7f982)
非常感谢您的回复，上面的截图是程序的调用栈信息对应的代码片段。

**Comment by PhoebeGaoZhen** [comment]
OK



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月12日 17:57 |
| 收件人 | ***@***.***> |
| 抄送至 | Gao, ***@***.***>***@***.***> |
| 主题 | Re: [PhoebeGaoZhen/AttentionGRN] data preprocessing Index Error (Issue #2) |

image.png (view on web)
image.png (view on web)
image.png (view on web)
非常感谢您的回复，上面的截图是程序的调用栈信息对应的代码片段。

**Comment by PhoebeGaoZhen** [comment]
您好！我们的模型是在Windows上开发的，所以在Windows上是可以正常运行的。

我一般是把项目保存在电脑本地，然后用pycharm2022版本打开data_preprocess项目。

数据是rawData，您只需要使用我提供的数据即可。

程序中需要设置Ranknums（Top N个基因，500 和1000都可以）、data_source（数据保存位置）、dataset_names（需要处理的细胞名称，这里需要注意的是，这个程序是可以处理一个细胞的数据的，但是我写了整理所有数据集信息的程序，所以如果只运行一个细胞的话，utils.dataset_Info(Ranknums, data_source)程序会报错，但不影响数据处理结果）




我看到您是在运行hHEP top 1000时出错，所以我检查了这个部分的程序，请检查是否与我的设置相同

在完成相同设置后，其他代码不需要任何变化，直接运行，结果如下：

可以发现，我这里读取到了11515个基因和425个细胞，这是正常的。而您读取的是2个基因和0个细胞，结果当然会报错。

上面对应的数据集是：


综上，建议您检查一下原始数据。另外，因为我没有在Windows以外的平台上运行过，所以我不清楚会出现什么错误，非常抱歉！
ps. 基本上只要您能读取到跟我一样的基因数量和细胞数量，就说明您找到的基因表达数据是正确的。


您是哪个大学的哪个老师的研究生吗？





At 2024-12-12 18:02:56, "高震" ***@***.***> wrote:

OK



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月12日 17:57 |
| 收件人 | ***@***.***> |
| 抄送至 | Gao, ***@***.***>***@***.***> |
| 主题 | Re: [PhoebeGaoZhen/AttentionGRN] data preprocessing Index Error (Issue #2) |

image.png (view on web)
image.png (view on web)
image.png (view on web)
非常感谢您的回复，上面的截图是程序的调用栈信息对应的代码片段。

**Comment by surqing** [comment]
不好意思，回复晚了，我之前有在邮件里直接回复，但是好像实际上并没有回复到issue中。我是中南大学的研一学生。后面我根据您的回复又进行了调试，但是并没有成功，我现在又在重新找GRN相关的可以用的代码，请问您方便添加联系方式交流吗，surqing@csu.edu.cn是我的邮箱
